# Resolve react_native_pods.rb with node to allow for hoisting
require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '16.0'
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']

use_frameworks! :linkage => :static

target 'BitPlayPro' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false,
    :fabric_enabled => true,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(installer)

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # Disable code signing on all Pod targets (Xcode 26 requirement)
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
        config.build_settings['CODE_SIGN_IDENTITY'] = ''
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'i386'

        # Fix fmt library consteval compilation error in Xcode 26 / Clang 17+
        # fmt uses C++20 consteval which Clang 17 rejects in certain contexts
        if target.name == 'fmt' || target.name.start_with?('glog')
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'FMT_USE_CONSTEVAL=0'
          config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
        end

        # Fix MMKVCore AESCrypt.cpp: memset_s undeclared in Xcode 26 / iOS 26.5 SDK
        # __STDC_WANT_LIB_EXT1__=1 enables C11 Annex K secure functions (memset_s etc.)
        if target.name == 'MMKVCore'
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << '__STDC_WANT_LIB_EXT1__=1'
          config.build_settings['OTHER_CPLUSPLUSFLAGS'] = '$(inherited) -D__STDC_WANT_LIB_EXT1__=1'
        end
      end
    end
  end

end
